name: CI Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: write
  packages: write

jobs:
  lint-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: x.18
          cache: 'npm'

      - name: Run lint and check
        run: |
          npm ci
          npm run lint
          npm run check

  build:
    runs-on: ubuntu-latest
    needs: lint-check

    # only run on main branch
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: x.18
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'

      - name: NPM install & version
        env:
          NODE_ENV: production
        run: |
          npm ci --include=dev
          npm version prerelease --preid=pre
          git config --global user.email "fake@nowhere.com"
          git config --global user.name "CI Build"

      - name: Build all bundles
        env:
          NODE_ENV: production
        run: |
          npm run build-bundle
          npm run build

      - name: Push back to GitHub
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: main

      - name: Publish prerelease to Github Packages
        run: |
          npm publish --tag=pre
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
