# Runs on release tag push, but not prereleases
name: Release & Publish

on:
  push:
    tags:
      - 'v*.*.*'
    tags-ignore:
      - 'v*.*.*-pre*'

permissions:
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: x.18
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'

      - name: Build all bundles
        env:
          NODE_ENV: production
        run: |
          npm ci --include=dev
          npm run build-bundle
          npm run build

      - name: Push dist-bundle back to GitHub
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: main

      - name: Publish full release to Github Packages
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
